[main]
protocol = "binary"     # Specify the protocol (binary, compact, json, simplejson)
framed = false          # Use framed transport
buffered = false        # Use buffered transport
addr = "localhost:9090" # Address to listen to
secure = true           # Use tls secure transport

[ledisdb]
addr = "localhost:6379"
password = ""
db = 0